travis:
  secure:
    BINSTAR_TOKEN: CijeFcvNJEBS7aes+22nxwJewdWTqxogpsBOBkXfLYVJBVA2RmCIDxJi0DTe2f/pW1jKkjGdXe5R4f+wRio/5VjXIYrTYGZJWuy7Mp8JV+1L5Tx85kc3JN4bkrLgF8cy6+kgUHHHKo8bn5LQ3GuhtetE1j+XIZ1MP9NJPu6szg8Kz0BnUpCgPfh89Pd6XVWNtoKzEmkCj0yAUIpXpBdRQPh5vkYBPz0wFURsfe7DXmR902NddiipNjLx+u/Sfpcs+IQERSaCwa5AJStXI3DkaDpoI95b9P2IR/O6esIBGr1OYsTyauT+jyGkOBpChbluxHrrQ4MK7GcHpaTNOmZUyQKKF6yBgxP+8ORmTrW4qioqT9pXF+dMRSAPU7g/VAm1HnHVcgJNyzPbSoN8UiBca779CR485ZByGsNalTZhEkpvy7H4e7i8msiPYyGYJmpgbbTWfjJmVPGlYkvfW1KNQcpYZbb8/e+tgFEZ1DIJAP7j2brxAZtJjT8DuBqXp2aUVxLfpZVgJbM5CPMIQ/ljXhUEAEKUq4FLY1PKplbEsdZSj3DWthTrQuhvwSXfq/5WgBCfMi5YiznGp3jiMtXk+2/m+u9iH730PxuHQIuBdmGqaPiEaxxeCYHkqYrxyhK/vgmpn5FwqPTxAI64eJXtDZnHewfOQeUzpGYP5I4XOoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
